language: java

jdk:
  - openjdk11

services:
  - docker

addons:
  sonarcloud:
    organization: $ORGANIZATION
    token: $SONARCLOUD_TOKEN

install:
  - curl https://cli-assets.heroku.com/install.sh | sh
  - cd codeceptjs-rest
  - npm init -y
  - npm install codeceptjs chai --save-dev
  - npm install mocha-junit-reporter mocha-multi --save
  - cd ..

script:


  - > # DEFINICION DE VARIABLES Y FUNCIONES DE CONTROL

    export step=0;
    export totalSteps=6;
    export stepName=(ignore);





  - > # CONSTRUCCION DE PROYECTO MAVEN Y ANALISIS DE SONAR

    step=$((step + 1));
    echo -e "\n\n\n\n\033[1m\e[33m ----- PASO $step DE $totalSteps INICIADO - ${stepName[$step]} ----- \n";

    cd server;
    mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar;

   if [[ "$?" = "1" ]]
     then echo -e "\n\033[1m\e[31m ----- PASO $step DE $totalSteps FALLIDO - ${stepName[$step]} ----- \n\n\n\n"
     exit 1
   fi;
   echo -e "\n\033[1m\e[32m ----- PASO $step DE $totalSteps EXITOSO - ${stepName[$step]} ----- \n\n\n\n";




  - > # CONSTRUCCION DE IMAGEN DE DOCKER

    step=$((step + 1));
    echo -e "\n\n\n\n\033[1m\e[33m ----- PASO $step DE $totalSteps INICIADO - ${stepName[$step]} ----- \n";

    docker build -t $ORGANIZATION/payroll-server:latest .;

   if [[ "$?" = "1" ]]
     then echo -e "\n\033[1m\e[31m ----- PASO $step DE $totalSteps FALLIDO - ${stepName[$step]} ----- \n\n\n\n";
     exit 1;
   fi;
   echo -e "\n\033[1m\e[32m ----- PASO $step DE $totalSteps EXITOSO - ${stepName[$step]} ----- \n\n\n\n";




  - > # TEST DE INTEGRACION

    step=$((step + 1));
    echo -e "\n\n\n\n\033[1m\e[33m ----- PASO $step DE $totalSteps INICIADO - ${stepName[$step]} ----- \n";

    docker run -d -e "PORT=$PORT" -p $PORT:$PORT $ORGANIZATION/payroll-server:latest;
    export tries=0;
    export max_tries=12;
    while [[ true ]]; do
      tries=$((tries + 1));
      echo "ESPERANDO SERVICIO... intento $tries de $max_tries";
      sleep 5;
      curl -G localhost:$PORT
      look_exit=$?;
      if [[ "$look_exit" = "0" ]]
        then echo -e "\nSERVICIO DISPONIBLE\n"
        break
      fi
      if [[ "$tries" -ge "$max_tries" ]]
        then echo -e "\nLIMITE DE TIEMPO ALCANZADO\n"
        exit 1
        break
      fi
    done;
    cd ../codeceptjs-rest;
    npx codeceptjs run --steps --reporter mocha-multi && cat output/result.xml;

   if [[ "$?" = "1" ]]
     then echo -e "\n\033[1m\e[31m ----- PASO $step DE $totalSteps FALLIDO - ${stepName[$step]} ----- \n\n\n\n"
     exit 1
   fi;
   echo -e "\n\033[1m\e[32m ----- PASO $step DE $totalSteps EXITOSO - ${stepName[$step]} ----- \n\n\n\n";




  - > # DESPLIEGUE A DOCKERHUB

    step=$((step + 1));
    echo -e "\n\n\n\n\033[1m\e[33m ----- PASO $step DE $totalSteps INICIADO - ${stepName[$step]} ----- \n";

    echo "$DOCKER_PASSWORD" | docker login -u $ORGANIZATION --password-stdin;
    docker push $ORGANIZATION/payroll-server:latest;

   if [[ "$?" = "1" ]]
     then echo -e "\n\033[1m\e[31m ----- PASO $step DE $totalSteps FALLIDO - ${stepName[$step]} ----- \n\n\n\n"
     exit 1
   fi;
   echo -e "\n\033[1m\e[32m ----- PASO $step DE $totalSteps EXITOSO - ${stepName[$step]} ----- \n\n\n\n";




  - > # DESPLIEGUE A HEROKU REGISTRY

    step=$((step + 1));
    echo -e "\n\n\n\n\033[1m\e[33m ----- PASO $step DE $totalSteps INICIADO - ${stepName[$step]} ----- \n";

    echo "$HEROKU_API_KEY" | docker login -u_ --password-stdin registry.heroku.com;
    docker tag $ORGANIZATION/payroll-server:latest registry.heroku.com/$HEROKU_APP_STAGING/web;
    docker push registry.heroku.com/$HEROKU_APP_STAGING/web;

   if [[ "$?" = "1" ]]
     then echo -e "\n\033[1m\e[31m ----- PASO $step DE $totalSteps FALLIDO - ${stepName[$step]} ----- \n\n\n\n"
     exit 1
   fi;
   echo -e "\n\033[1m\e[32m ----- PASO $step DE $totalSteps EXITOSO - ${stepName[$step]} ----- \n\n\n\n";




  - > # RELEASE DE HEROKU APP STAGING

    step=$((step + 1));
    echo -e "\n\n\n\n\033[1m\e[33m ----- PASO $step DE $totalSteps INICIADO - ${stepName[$step]} ----- \n";

    heroku container:release web --app=$HEROKU_APP_STAGING; 

   if [[ "$?" = "1" ]]
     then echo -e "\n\033[1m\e[31m ----- PASO $step DE $totalSteps FALLIDO - ${stepName[$step]} ----- \n\n\n\n"
     exit 1
   fi;
   echo -e "\n\033[1m\e[32m ----- PASO $step DE $totalSteps EXITOSO - ${stepName[$step]} ----- \n\n\n\n";


