language: java

jdk:
  - openjdk11

services:
  - docker

addons:
  sonarcloud:
    organization: "francobobadilla"
    token: ad5a121aaef2acbe16431683b60dc9daead13e26

script:
  - cd server
  - mvn clean package spring-boot:repackage
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  - docker build -t payroll-server .
  - docker images
  - docker login -u francobobadilla -p apich4594*
  - docker tag payroll-server francobobadilla/payroll-server:latest
  - docker push francobobadilla/payroll-server:latest
  - curl https://cli-assets.heroku.com/install.sh | sh
  - echo b75a94b7-b267-4e0f-8457-f96df4caab68 | docker login -u_ --password-stdin registry.heroku.com
  - docker tag francobobadilla/payroll-server:latest registry.heroku.com/payroll-server-bobadilla/web
  - heroku container:push web --app=payroll-server-bobadilla
  - heroku container:release web --app=payroll-server-bobadilla
