language: java

jdk:
  - openjdk11

services:
  - docker

addons:
  sonarcloud:
    organization: $ORGANIZATION
    token: $SONARCLOUD_TOKEN

install:
  - curl https://cli-assets.heroku.com/install.sh | sh
  - cd codeceptjs-rest
  - npm init -y
  - npm install codeceptjs chai --save-dev
  - npm install mocha-junit-reporter mocha-multi --save
  - cd ..

script:


  - > # DEFINICION DE VARIABLES Y FUNCIONES DE CONTROL

    step=0;

    stepInit () {
      step=$((step + 1));
      stepName=$1;
      stepPrint INICIADO;
    };

    stepFinish () {
      if [[ "$?" = "1" ]]
        then stepPrint FALLIDO;
        sleep 2;
        exit 1;
      fi;
      stepPrint EXITOSO;
    };

    stepPrint () {
      case "$1" in
      "INICIADO")
        echo -e "\n\n\n\n\033[1m\e[33m ----- PASO $step $1 - $stepName ----- \n"
        ;;
      "FALLIDO")
        echo -e "\n\033[1m\e[31m ----- PASO $step $1 - $stepName ----- \n\n\n\n"
        ;;
      "EXITOSO")
        echo -e "\n\033[1m\e[32m ----- PASO $step $1 - $stepName ----- \n\n\n\n"
        ;;
      esac
    };




  - > # CONSTRUCCION DE PROYECTO MAVEN Y ANALISIS DE SONAR

    stepInit "CONSTRUCCION DE PROYECTO MAVEN Y ANALISIS DE SONAR";

    cd server;
    mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar;

    stepFinish;




  - > # CONSTRUCCION DE IMAGEN DE DOCKER

    stepInit "CONSTRUCCION DE IMAGEN DE DOCKER";

    docker build -t $ORGANIZATION/payroll-server:latest .;

    stepFinish;




  - > # TEST DE INTEGRACION

    stepInit "TEST DE INTEGRACION";

    docker run -d -e "PORT=$PORT" -p $PORT:$PORT $ORGANIZATION/payroll-server:latest;
    export tries=0;
    export max_tries=12;
    while [[ true ]]; do
      tries=$((tries + 1));
      echo "ESPERANDO SERVICIO... intento $tries de $max_tries";
      sleep 5;
      curl -G localhost:$PORT
      look_exit=$?;
      if [[ "$look_exit" = "0" ]]
        then echo -e "\nSERVICIO DISPONIBLE\n"
        break
      fi
      if [[ "$tries" -ge "$max_tries" ]]
        then echo -e "\nLIMITE DE TIEMPO ALCANZADO\n"
        exit 1
        break
      fi
    done;
    cd ../codeceptjs-rest;
    npx codeceptjs run --steps --reporter mocha-multi && cat output/result.xml;

    stepFinish;




  - > # DESPLIEGUE A DOCKERHUB

    stepInit "DESPLIEGUE A DOCKERHUB";

    echo "$DOCKER_PASSWORD" | docker login -u $ORGANIZATION --password-stdin;
    docker push $ORGANIZATION/payroll-server:latest;

    stepFinish;




  - > # DESPLIEGUE A HEROKU REGISTRY

    stepInit "DESPLIEGUE A HEROKU REGISTRY";

    echo "$HEROKU_API_KEY" | docker login -u_ --password-stdin registry.heroku.com;
    docker tag $ORGANIZATION/payroll-server:latest registry.heroku.com/$HEROKU_APP_STAGING/web;
    docker push registry.heroku.com/$HEROKU_APP_STAGING/web;

    stepFinish;




  - > # RELEASE DE HEROKU APP STAGING

    stepInit "RELEASE DE HEROKU APP STAGING";

    heroku container:release web --app=$HEROKU_APP_STAGING; 

    stepFinish;


