language: java

jdk:
  - openjdk11


script:


  - > # DEFINICION DE VARIABLES Y FUNCIONES DE CONTROL

    export step=0;
    export totalSteps=6;
    export stepName=(ignore);

    export stepName[1]="CONSTRUCCION DE PROYECTO MAVEN Y ANALISIS DE SONAR";
    stepName[2]="CONSTRUCCION DE IMAGEN DE DOCKER";
    stepName[3]="TEST DE INTEGRACION";
    stepName[4]="DESPLIEGUE A DOCKERHUB";
    stepName[5]="DESPLIEGUE A HEROKU REGISTRY";
    stepName[6]="RELEASE DE HEROKU APP STAGING";

    stepInit () {
      step=$((step + 1));
      echo -e "\n\n\n\n\033[1m\e[33m ----- PASO $step DE $totalSteps INICIADO - ${stepName[$step]} ----- \n";
      echo -e "\nA${stepName[$step]}";
    };

    stepFinish () {
      if [[ "$1" = "1" ]]
        then echo -e "\n\033[1m\e[31m ----- PASO $step DE $totalSteps FALLIDO - ${stepName[$step]} ----- \n\n\n\n"
        exit 1
      fi;
    };



  - > # CONSTRUCCION DE PROYECTO MAVEN Y ANALISIS DE SONAR

    stepInit;


