language: java

jdk:
  - openjdk11

services:
  - docker

addons:
  sonarcloud:
    organization: $ORGANIZATION
    token: $SONARCLOUD_TOKEN

jobs:
  include:
    - stage: install
      script: cd codeceptjs-rest
      script: npm init -y
      script: npm install codeceptjs chai --save-dev
      script: cd ..
      script: curl https://cli-assets.heroku.com/install.sh | sh
    - stage: login
      script:
      script: echo "$DOCKER_PASSWORD" | docker login -u $ORGANIZATION --password-stdin
      script: echo "$HEROKU_API_KEY" | docker login -u_ --password-stdin registry.heroku.com
    - stage: build and test
      script:
      script: cd server
      script: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
      script: docker build -t $ORGANIZATION/payroll-server:latest .
      script: docker run -d -e "PORT=$PORT" -p $PORT:$PORT $ORGANIZATION/payroll-server:latest
      script: >
          export tries=0;
          export max_tries=12;
          while [[ true ]]; do
            tries=$((tries + 1));
            echo "esperando servicio... intento [$tries] de [$max_tries]";
            sleep 5;
            curl -G localhost:$PORT
            look_exit=$?;
            if [[ "$look_exit" = "0" ]]
               then echo "servicio disponible"
               break
            fi
            if [[ "$tries" -ge "$max_tries" ]]
               then echo "límite de tiempo alcanzado"
               exit 1
               break
           fi
           done;
      script: cd ../codeceptjs-rest
      script: npx codeceptjs run --steps
    - stage: deploy
      script:
      script: docker push $ORGANIZATION/payroll-server:latest
      script: docker tag $ORGANIZATION/payroll-server:latest registry.heroku.com/$HEROKU_APP_STAGING/web
      script: docker push registry.heroku.com/$HEROKU_APP_STAGING/web
      script: heroku container:release web --app=$HEROKU_APP_STAGING
