language: java

jdk:
  - openjdk11

services:
  - docker

addons:
  sonarcloud:
    organization: $ORGANIZATION
    token: $SONARCLOUD_TOKEN

script:
  - cd server
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  - docker build -t payroll-server .
  - docker run -d -e "PORT=$PORT" -p $PORT:$PORT payroll-server
  - >
    export tries=0;
    export max_tries=12;
    while [[ true ]]; do
      tries=$((tries + 1));
      echo "esperando servicio... intento [$tries] de [$max_tries]";
      sleep 5;
      curl -G localhost:$PORT
      look_exit=$?;
      if [[ "$look_exit" = "0" ]]
         then echo "servicio disponible"
         break
      fi
      if [[ "$tries" -ge "$max_tries" ]]
         then echo "límite de tiempo alcanzado"
         exit 1
         break
     fi
     done;
  - cd ../codeceptjs-rest
  - npm init -y
  - npm install codeceptjs chai --save-dev
  - npx codeceptjs run --steps
  - docker login -u $ORGANIZATION -p $DOCKER_PASSWORD
  - docker tag payroll-server $ORGANIZATION/payroll-server:latest
  - docker push $ORGANIZATION/payroll-server:latest
  - curl https://cli-assets.heroku.com/install.sh | sh
  - echo "$HEROKU_API_KEY" | docker login -u_ --password-stdin registry.heroku.com
  - docker tag $ORGANIZATION/payroll-server:latest registry.heroku.com/$HEROKU_APP_STAGING/web
  - docker push registry.heroku.com/$HEROKU_APP_STAGING/web
  - heroku container:release web --app=$HEROKU_APP_STAGING
