language: java

jdk:
  - openjdk11

services:
  - docker

script:
  - cd server
  - ls -la
  - mvn clean package spring-boot:repackage  
  - docker build -t payroll-server .
  - docker images
  - docker login -u francobobadilla -p apich4594*
  - docker tag payroll-server francobobadilla/payroll-server:latest
  - docker push francobobadilla/payroll-server:latest
  - curl https://cli-assets.heroku.com/install.sh | sh
  - heroku login

