language: java

jdk:
  - openjdk11

services:
  - docker

script:
  - cd server
  - ls -la
  - mvn clean package spring-boot:repackage  
  - docker build -t payroll-server .
  - docker images
  - docker login -u francobobadilla -p apich4594*
  - docker tag payroll-server francobobadilla/payroll-server:latest
  - docker push francobobadilla/payroll-server:latest
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo apich4594* | docker login -u 1709673@ucc.edu.ar --password-stdin registry.heroku.com

