language: java

jdk:
  - openjdk11

services:
  - docker

addons:
  sonarcloud:
    organization: $ORGANIZATION
    token: $SONARCLOUD_TOKEN

install:
  - curl https://cli-assets.heroku.com/install.sh | sh
  - cd codeceptjs-rest
  - npm init -y
  - npm install codeceptjs chai --save-dev
  - npm install mocha-junit-reporter mocha-multi --save
  - cd ..

script:
  - > # DEFINICION DE VARIABLES DE CONTROL

    export step=0;
    export totalSteps=6;




  - > # CONSTRUCCION DE PROYECTO MAVEN Y ANALISIS DE SONAR

    step=$((step + 1));
    echo -e "\n\n\n\n\033[1m\e[33m ----- COMENZANDO BUILD - PASO $step DE $totalSteps ----- \n";

    cd server;
    mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar;

    look_exit=$?;
    if [[ "$look_exit" = "1" ]]
      then echo -e "\n\033[1m\e[31m ----- BUILD FALLIDO - PASO $step DE $totalSteps ----- \n\n\n\n"
      exit 1
    fi;
    echo -e "\n\033[1m\e[32m ----- BUILD EXITOSO - PASO $step DE $totalSteps ----- \n\n\n\n";




  - > # CONSTRUCCION DE IMAGEN DE DOCKER

    step=$((step + 1));
    echo -e "\n\n\n\n\033[1m\e[33m ----- COMENZANDO CONSTRUCCION DE IMAGEN DE DOCKER - PASO $step DE $totalSteps ----- \n";

    docker build -t $ORGANIZATION/payroll-server:latest .;

    look_exit=$?;
    if [[ "$look_exit" = "1" ]]
      then echo -e "\n\033[1m\e[31m ----- CONSTRUCCION FALLIDA - PASO $step DE $totalSteps ----- \n\n\n\n"
      exit 1
    fi;
    echo -e "\n\033[1m\e[32m ----- CONSTRUCCION EXITOSA - PASO $step DE $totalSteps ----- \n\n\n\n";




  - > # TEST DE INTEGRACION

    step=$((step + 1));
    echo -e "\n\n\n\n\033[1m\e[33m ----- COMENZANDO TEST DE INTEGRACION - PASO $step DE $totalSteps ----- \n";

    docker run -d -e "PORT=$PORT" -p $PORT:$PORT $ORGANIZATION/payroll-server:latest;
    export tries=0;
    export max_tries=12;
    while [[ true ]]; do
      tries=$((tries + 1));
      echo "ESPERANDO SERVICIO... intento $tries de $max_tries";
      sleep 5;
      curl -G localhost:$PORT
      look_exit=$?;
      if [[ "$look_exit" = "0" ]]
        then echo -e "\nSERVICIO DISPONIBLE\n"
        break
      fi
      if [[ "$tries" -ge "$max_tries" ]]
        then echo -e "\nLIMITE DE TIEMPO ALCANZADO\n"
        exit 1
        break
      fi
    done;
    cd ../codeceptjs-rest;
    npx codeceptjs run --steps --reporter mocha-multi;

    look_exit=$?;
    cat output/result.xml;
    if [[ "$look_exit" = "1" ]]
      then echo -e "\n\033[1m\e[31m ----- TEST DE INTEGRACION FALLIDO - PASO $step DE $totalSteps ----- \n\n\n\n"
      exit 1
    fi;
    echo -e "\n\n\033[1m\e[32m ----- TEST DE INTEGRACION EXITOSO - PASO $step DE $totalSteps ----- \n\n\n\n";




  - > # DESPLIEGUE A DOCKERHUB

    step=$((step + 1));
    echo -e "\n\n\n\n\033[1m\e[33m ----- COMENZANDO DESPLIEGUE A DOCKERHUB - PASO $step DE $totalSteps ----- \n";

    echo "$DOCKER_PASSWORD" | docker login -u $ORGANIZATION --password-stdin;
    docker push $ORGANIZATION/payroll-server:latest;

    look_exit=$?;
    if [[ "$look_exit" = "1" ]]
      then echo -e "\n\033[1m\e[31m ----- DESPLIEGUE A DOCKERHUB FALLIDO - PASO $step DE $totalSteps ----- \n\n\n\n"
      exit 1
    fi;
    echo -e "\n\033[1m\e[32m ----- DESPLIEGUE A DOCKERHUB EXITOSO - PASO $step DE $totalSteps ----- \n\n\n\n";




  - > # DESPLIEGUE A HEROKU REGISTRY

    step=$((step + 1));
    echo -e "\n\n\n\n\033[1m\e[33m ----- COMENZANDO DESPLIEGUE A HEROKU REGISTRY - PASO $step DE $totalSteps ----- \n";

    echo "$HEROKU_API_KEY" | docker login -u_ --password-stdin registry.heroku.com;
    docker tag $ORGANIZATION/payroll-server:latest registry.heroku.com/$HEROKU_APP_STAGING/web;
    docker push registry.heroku.com/$HEROKU_APP_STAGING/web;

    look_exit=$?;
    if [[ "$look_exit" = "1" ]]
      then echo -e "\n\033[1m\e[31m ----- DESPLIEGUE A HEROKU REGISTRY FALLIDO - PASO $step DE $totalSteps ----- \n\n\n\n"
      exit 1
    fi;
    echo -e "\n\033[1m\e[32m ----- DESPLIEGUE A HEROKU REGISTRY EXITOSO - PASO $step DE $totalSteps ----- \n\n\n\n";




  - > # RELEASE DE HEROKU APP STAGING

    step=$((step + 1));
    echo -e "\n\n\n\n\033[1m\e[33m ----- COMENZANDO RELEASE DE HEROKU APP STAGING - PASO $step DE $totalSteps ----- \n";

    heroku container:release web --app=$HEROKU_APP_STAGING; 

    look_exit=$?;
    if [[ "$look_exit" = "1" ]]
      then echo -e "\n\033[1m\e[31m ----- RELEASE DE HEROKU APP STAGING FALLIDO - PASO $step DE $totalSteps ----- \n\n\n\n"
      exit 1
    fi;
    echo -e "\n\033[1m\e[32m ----- RELEASE DE HEROKU APP STAGING EXITOSO - PASO $step DE $totalSteps ----- \n\n\n\n";



